MASSHUU12/ipz

.github/workflows/update-dependencies.yml
=> chore: create update-dependencies.yml

codeception.yml, composer.json, composer.lock, tests/Acceptance.suite.yml, tests/Functional.suite.yml, tests/Support/AcceptanceTester.php, tests/Support/FunctionalTester.php, tests/Support/UnitTester.php, tests/Support/_generated/.gitignore, tests/Unit.suite.yml, tests/_output/.gitignore
=> Add Test Files

app/Http/Controllers/AuthController.php, app/Models/User.php, composer.json, composer.lock, docs/api/USER_ENDPOINTS.md, docs/api/bruno/Auth/Register.bru, lang/en/auth.php, lang/en/pagination.php, lang/en/passwords.php, lang/en/validation.php
Wprowadza poprawną walidację numeru telefonu.
Close #30
- Testy manualne
N/A
=> feat: proper phone number validation

app/Http/Controllers/AuthController.php, app/Http/Middleware/CheckUserBlocked.php, app/Models/User.php, database/migrations/2025_03_20_095223_add_failed_login_fields_to_users_table.php, docs/api/USER_ENDPOINTS.md, routes/api.php
Wprowadza blokowanie konta użytkownika na 4 godziny po 5 nieudanych próbach logowania.
Gdy konto jest zablokowane żadne akcje na chronionych endpointach nie wykonają się nawet z poprawnym tokenem.
Zwiększa ochronę konta użytkownika przed atakami typu brute force.
N/A
Brak.
=> Implement account blocking

app/Http/Controllers/UserController.php, docs/api/AUTH_ENDPOINTS.md, docs/api/USER_ENDPOINTS.md, docs/api/bruno/User/Delete User.bru, docs/api/bruno/User/Get User.bru, docs/api/bruno/User/Patch User.bru, routes/api.php
Wprowadza poniższe endpointy oraz dokumentację dla nich:
```txt
GET /user
Zwraca informacje o zalogowanym użytkowniku
PATCH /user
Pozwala na aktualizację informacji o zalogowanym użytkowniku
DELETE /user
Usuwa konto zalogowanego użytkownika
```
Bez tego powyższe akcje nie byłyby możliwe do wykonania.
N/A
Nie zauważono.
=> feat(API): allow getting and editing user info, and user deletion

app/Facades/Gios.php, app/Http/Controllers/AirQualityController.php, app/Providers/GiosServiceProvider.php, app/Services/GiosApi.php, bootstrap/providers.php, docs/api/air_quality_endpoints.yml, docs/api/bruno/Air Quality/Air Quality.bru, docs/api/bruno/Air Quality/folder.bru, routes/api.php
Integruje API GIOŚ, oraz dodaje testowy endpoint (wraz z dokumentacją) do pobierania jakości powietrza dla wybranej lokalizacji `/api/air-quality`.
Close #72 #80
Brak.
=> feat(backend): create class to handle GIOŚ API

app/Http/Controllers/AuthController.php, docs/api/auth_endpoints.yml, docs/api/bruno/Auth/Validate Token.bru, routes/api.php
=> feat(backend): create /token/validate endpoint

bun.lock, package.json
DODANIE ZALEZNOŚCI PLAYWRIGHT DO PROJEKTU.
AUTOMATYZACJE TESTÓW FRONTEND
URUCHAMIANIE TESTÓW W TRZECH PRZEGLĄDARKACH DO 
WYBORU
- CHROMIUM
- FIREFOX
- WEBKIT
=> add dependencies playwright + test web site

app/Http/Controllers/UserPreferenceController.php, app/Models/User.php, app/Models/UserPreference.php, app/Observers/UserObserver.php, app/Providers/AppServiceProvider.php, database/migrations/2025_04_02_075252_create_user_preferences_table.php, docs/api/bruno/User/Get Preferences.bru, docs/api/bruno/User/Update Preferences.bru, docs/api/user_preferences_endpoints.yml, routes/api.php
Close #94
Close #95
- manual testing
None.
=> feat: create user preferences

README.md, app/Http/Controllers/AuthController.php, app/Models/User.php, app/Providers/AppServiceProvider.php, bootstrap/app.php, composer.json, composer.lock, config/permission.php, database/migrations/2025_04_03_075748_create_permission_tables.php, database/seeders/DatabaseSeeder.php, database/seeders/RolesAndPermissionsSeeder.php, docs/api/bruno/Admin Test.bru, docs/api/bruno/collection.bru, docs/api/user_endpoints.yml, routes/api.php, tests/Feature/Auth/RegistrationTest.php, vite.config.ts
Wprowadza uprawnienia i role użytkowników, co pozwoli na ograniczanie dostępu do określonych endpointów.
N/A
- unit tests
- manual tests
None.
=> feat(backend): implement permissions

.env.example, bun.lock, e2e/example2.spec.ts, package.json, resources/js/api/api.ts, resources/js/api/userApi.ts, resources/js/pages/admin.tsx, resources/views/app.blade.php, routes/web.php
Dodaje prostą stronę administratora, oraz tworzy podstawy pod proste zapytania do serwera.
Aby ułatwiać testowanie, oraz wysyłanie zapytań do serwera.
Close #117
N/A
=> feat(frontend): create basic admin page

app/Http/Controllers/ImgwController.php, app/Services/ImgwApiClient.php, docs/api/bruno/IMGW/Hydrological data.bru, docs/api/bruno/IMGW/Hydrological warnings.bru, docs/api/bruno/IMGW/Meteorological data.bru, docs/api/bruno/IMGW/Meteorological warnings.bru, docs/api/bruno/IMGW/Product resources.bru, docs/api/bruno/IMGW/Synoptic data.bru, docs/api/bruno/IMGW/folder.bru, docs/api/imgw_endpoints.yml, routes/api.php
=> feat(backend): handle Dane Publiczne

.editorconfig, app/Http/Controllers/AuthController.php, docs/api/auth_endpoints.yml
=> fix(auth): duplicate phone numbers can bypass validation

database/migrations/2025_04_17_094523_create_air_pollution_historical_data_table.php, database/migrations/2025_04_17_094539_create_air_pollution_leaderboard_table.php
=> feat(database): create tables for historical air pollution & leaderboard

app/Console/Commands/CreateNewLeaderboardCommand.php, app/Console/Commands/DeleteOldAirPollutionDataCommand.php, app/Console/Commands/StoreCurrentAirPollutionCommand.php, app/Jobs/CreateNewLeaderboard.php, app/Models/AirPollutionLeaderboard.php, bootstrap/app.php, database/migrations/2025_04_17_094539_create_air_pollution_leaderboard_table.php
=> feat: create leaderboard based on historical data

app/Http/Controllers/LeaderboardController.php, docs/api/bruno/Air Quality/Leaderboard.bru, docs/api/leaderboard_endpoints.yml, routes/api.php
=> feat: create endpoints for leaderboard

app/Data/StationData.php, app/Http/Controllers/AirQualityController.php, app/Http/Requests/GetAirQualityRequest.php, app/Jobs/StoreCurrentAirPollution.php, app/Models/AirPollutionHistoricalData.php, app/Services/AirQualityService.php, database/migrations/2025_04_17_094523_create_air_pollution_historical_data_table.php, docs/api/air_quality_endpoints.yml, routes/api.php
=> feat(backend): use historical data for existing endpoint

app/Http/Controllers/UserFavoriteLocationsController.php, app/Http/Requests/StoreFavoriteLocationRequest.php, app/Http/Requests/UpdateFavoriteLocationRequest.php, app/Models/User.php, app/Models/UserFavoriteLocation.php, database/migrations/2025_05_03_115928_create_user_favorite_locations_table.php, docs/api/bruno/Favorite locations/Delete Location.bru, docs/api/bruno/Favorite locations/Get Location.bru, docs/api/bruno/Favorite locations/Get Locations.bru, docs/api/bruno/Favorite locations/Patch Location.bru, docs/api/bruno/Favorite locations/Post Location.bru, docs/api/bruno/Favorite locations/folder.bru, docs/api/favorite_locations_endpoints.yml, routes/api.php
=> feat(backend): favorite locations

database/factories/UserPreferenceFactory.php, e2e/1registration_page_test.spec.ts, e2e/2login_page_tests.spec.ts, e2e/login_page_tests.spec.ts, tests/Feature/UserPreferencesTest.php, tests/Unit/UserPreferenceTest.php
=> User preferences test

tests/Feature/AdminTest.php, tests/Feature/Auth/UserPreferencesTest.php, tests/Feature/Auth/UserTest.php, tests/Feature/Auth/ValidateTokenTest.php
=> add User endpiont Test

tests/Feature/AirPollutionCommandTest.php, tests/Feature/Database/MigrationsTest.php, tests/Unit/CreateNewLeaderboardJobTest.php
=> add test with database

.github/workflows/run_phpunit_tests.yml, .github/workflows/run_playwright_tests.yml
=> chore: run tests on PR only when necessary

app/Http/Controllers/AuthController.php, app/Http/Controllers/UserController.php, app/Http/Requests/LoginRequest.php, app/Http/Requests/RegisterRequest.php, app/Http/Requests/UpdatePasswordRequest.php, docs/api/auth_endpoints.yml, docs/api/bruno/Auth/Login.bru, docs/api/bruno/User/Patch User.bru, docs/api/bruno/User/Update Password.bru, docs/api/user_endpoints.yml, routes/api.php
=> feat(backend): proper password update

app/Console/Commands/StoreCurrentSynopticDataCommand.php, app/Http/Requests/RegisterRequest.php, app/Jobs/StoreCurrentSynopticData.php, app/Models/SynopticHistoricalData.php, bootstrap/app.php, database/migrations/2025_05_05_113735_create_synoptic_historical_data_table.php
Potrzebne do wykonania #213, dodatkowo pozwoli na ograniczenie zapytań do zewnętrznego API.
=> feat(backend): store synoptic historical data

app/Http/Controllers/ImgwController.php
Potrzebne do wykonania #213, dodatkowo pozwala na ograniczenie zapytań do zewnętrznego API.
=> feat(backend): use synoptic historical data in the ImgwController

app/Http/Controllers/ImgwController.php
=> feat(backend): try fuzzy-matching against station names

app/Http/Controllers/AuthController.php
=> fix(backend): exception when logging on nonexistent account

app/Http/Controllers/ImgwController.php, app/Jobs/StoreCurrentSynopticData.php, app/Services/ImgwApiClient.php, docs/api/bruno/IMGW/Synoptic data.bru, docs/api/imgw_endpoints.yml, resources/js/api/synopApi.ts
=> fix(backend): #297

app/Http/Requests/GetAirQualityRequest.php
=> fix(backend): /air-quality returns 404 when db is empty

app/Http/Controllers/AuthController.php, docs/api/auth_endpoints.yml
=> feat(backend): invalidate all user tokens after password change

resources/js/components/ErrorBoundary.tsx, resources/js/pages/dashboard/AirPollutionChart.tsx, resources/js/pages/dashboard/Dashboard.tsx, resources/js/pages/dashboard/WeatherCard.tsx
=> feat(frontend): handle errors in dashboard

app/Helpers/JaroWinklerHelper.php, app/Http/Controllers/AddressSuggestionController.php, app/Http/Requests/GetAirQualityRequest.php
=> feat(backend): improve address comparison
